# name of the software
name: Oppslagstjeneste .NET
siteUrlText: http://difi.github.io/oppslagstjeneste-klient-dotnet
# current version of the software
version: 0.1
# url of the download button
downloadUrl: https://www.nuget.org/packages/difi-oppslagstjeneste-klient/
# licence of the software
license: Apace Licence 2.0
licenseUrl: https://www.apache.org/licenses/LICENSE-2.0

baseurl: "/oppslagstjeneste-klient-dotnet"

##Version handling
currentCollecion: "v5_3"
currentVersion: "5.3"
versions: ["5.3","5.1-5.2","5.0","1.0"]

# Collection of versions
collections:
  v1_0:  
    output: true
    permalink: /v1.0/
  v5_0:  
    output: true
    permalink: /v5.0/
  v5_1_2:  
    output: true
    permalink: /v5.1-5.2/
  v5_3:  
    output: true
    permalink: /v5.3/
aboutSide: "about.html"

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/difi/oppslagstjeneste-klient-dotnet
  - title: Om oppslagstjenesten
    url: /oppslagstjeneste-klient-dotnet/about.html
  - title: Issues
    url: https://github.com/difi/oppslagstjeneste-klient-dotnet/issues

# list if additional links on the footer
footerLinks:
  - title: Om oppslagstjenesten
    url: /oppslagstjeneste-klient-dotnet/about.html
  - title: GitHub
    url: https://github.com/difi/oppslagstjeneste-klient-dotnet
  - title: Issues
    url: https://github.com/difi/oppslagstjeneste-klient-dotnet/issues

# header
header:
  color1: "#606369"
  color2: "#4D4F53"
  trianglify: true

# github buttons
githubButton:
  user: difi
  repo: difi/oppslagstjeneste-klient-dotnet

# twitter buttons
twitter:
  enabled: false
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: false
  profileUrl:

# google analytics
analytics:
  trackingid: UA-78356843-1
  domain: auto

# DON'T MODIFY
highlight: rouge

gems:
  - jekyll-redirect-from

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']

kramdown:
  input: GFM
  
